### ISSUE TITLE
wrong closing tag in readme example

### ISSUE THREAD

**Issue by WonderLabWoman** [rvdleun/aframe-arcube#1]
...just a little typo ;)

In the readme, the first example below the 'Properties' says: 
```
<a-entity ar-cube="scale: 2; timeout: 2000">
  <a-sphere src="#earth"></a-sphere>
</a-arcube>

```
The last closing tag should of course be `</a-entity>`

**Comment by rvdleun** [comment]
Very sharp eye. Updated the README.md in the latest release.
